[[SoftPosit]]
arch = "i686"
git-tree-sha1 = "4001a9d35945e0e852f50efab5f8db46752f37b8"
libc = "musl"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "8ea9829aa32510d534f495147f677742333c7fe154f12d87396bc613aa56e933"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.i686-linux-musl.tar.gz"
[[SoftPosit]]
arch = "aarch64"
git-tree-sha1 = "f47bae10d00aede6e7fbd3252d9a02f87ea31dd6"
libc = "musl"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "33707c41aeacfa06912bd454d0acb99547320e116fa8d2762db52b2a9f772bcd"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.aarch64-linux-musl.tar.gz"
[[SoftPosit]]
arch = "i686"
git-tree-sha1 = "ecfccdc02f202cf856a158bf908a4e82c159788b"
os = "windows"

    [[SoftPosit.download]]
    sha256 = "5ac6269848c63236421c3a51d3b429f0b35a3b0c5cd5ba17a79519a7d471fb29"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.i686-w64-mingw32.tar.gz"
[[SoftPosit]]
arch = "x86_64"
git-tree-sha1 = "2a59ecf4e5fc3d29d744363e23e98d4d51813772"
os = "windows"

    [[SoftPosit.download]]
    sha256 = "e5de00db652432032e0de3a8b831529187c5108ad7d045e510fe861e4cb7c5cb"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.x86_64-w64-mingw32.tar.gz"
[[SoftPosit]]
arch = "armv7l"
git-tree-sha1 = "8ff0066b17457de3d9f06609d61705046479e6d3"
libc = "glibc"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "80001e798d132647afecc70c2c171e0a5686698cbf92d1f4059489c39930f9dc"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.armv7l-linux-gnueabihf.tar.gz"
[[SoftPosit]]
arch = "armv7l"
git-tree-sha1 = "84dede3d2ea2d58c446b2fd9f7ff1418f21f9ad7"
libc = "musl"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "17c5213bd546118b72fd54391c2129c5531e61614efb62209ab94216493cc2f6"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.armv7l-linux-musleabihf.tar.gz"
[[SoftPosit]]
arch = "i686"
git-tree-sha1 = "19f1a5ed4d01647e8ad63ed1a06f3e7e81096a80"
libc = "glibc"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "49b1fddfa3ab7708eb64053d395ac00d87f989a4e30681f9ce9011f973574356"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.i686-linux-gnu.tar.gz"
[[SoftPosit]]
arch = "x86_64"
git-tree-sha1 = "12aa3bb2e47b0ca153ecc791b67890a199c20afa"
libc = "glibc"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "165e1bdf52578a8a2e689f2c602ec6e84d27f1740fb3936e00279804ec3f5ed8"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.x86_64-linux-gnu.tar.gz"
[[SoftPosit]]
arch = "powerpc64le"
git-tree-sha1 = "885f9a0147237f0524842f3c6ef6f8876c2112ee"
libc = "glibc"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "c5de038c2af4dc4e9da59695255e34759db5c06ef2ee89e9bcde6ed0c1176350"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.powerpc64le-linux-gnu.tar.gz"
[[SoftPosit]]
arch = "x86_64"
git-tree-sha1 = "e9210901eb2dc0fca5c11312066e4435fd238752"
os = "macos"

    [[SoftPosit.download]]
    sha256 = "ef902dc9a310c8b0181c58aee2fddf60ae8392fa840fb0e61b78d8db84720d8b"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.x86_64-apple-darwin14.tar.gz"
[[SoftPosit]]
arch = "aarch64"
git-tree-sha1 = "8645d4ddb3a8f7404274954bc403cdc1df8c0c23"
libc = "glibc"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "b0fbda0a19d0bdd91eac937a7f5b56fa8fefcb110940b9aeefd800a358935a2b"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.aarch64-linux-gnu.tar.gz"
[[SoftPosit]]
arch = "x86_64"
git-tree-sha1 = "cc6c19a1dadc16a09aace25d4beb03c140ce6501"
os = "freebsd"

    [[SoftPosit.download]]
    sha256 = "898d0dc9df47e533e7a0365ff287576df37ff0c3d755f3e9ee55d688a059c99f"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.x86_64-unknown-freebsd11.1.tar.gz"
[[SoftPosit]]
arch = "x86_64"
git-tree-sha1 = "cc61cf87b2f4fe484063af24b9e9754e8e1417c4"
libc = "musl"
os = "linux"

    [[SoftPosit.download]]
    sha256 = "67227576aa6c3ebb8f2ab0b39c223c9634322f0f823bc9ff11940ed95b87f718"
    url = "https://github.com/JuliaBinaryWrappers/SoftPosit_jll.jl/releases/download/SoftPosit-v0.4.1+1/SoftPosit.v0.4.1.x86_64-linux-musl.tar.gz"
